#!/bin/bash -x

JOB_DIR=/var/vcap/jobs/riak
RIAK_HEALTH=/var/vcap/jobs/riak/bin/riak_health.sh
RUN_DIR=/var/vcap/sys/run/riak
LOG_DIR=/var/vcap/sys/log/riak
PIDFILE=$RUN_DIR/riak_health.pid

case $1 in

  start)
    for DIR in $RUN_DIR $LOG_DIR
      do
        mkdir -p $DIR
        chown vcap:vcap $DIR
      done

    # Start health monitor
    ${RIAK_HEALTH} &

    ;;

  stop)
    kill `cat ${PIDFILE}`
    rm -f $PIDFILE
    ;;

  *)
    echo "Usage: riak_health_ctl {start|stop}" ;;
esac
exit 0
